'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Update_Inventory
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''lblAddGenre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddGenre As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblGenreAddName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGenreAddName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtAddGenre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddGenre As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblRemove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRemove As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlGenreRemove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlGenreRemove As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''GenreRemove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GenreRemove As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''btnAddGenre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddGenre As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnRemove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRemove As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblARRelease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblARRelease As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAddRelease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddRelease As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtAddRelease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddRelease As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblRemoveRelease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRemoveRelease As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlRemoveRelease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRemoveRelease As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ReleaseRemove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReleaseRemove As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''btnAddrelease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddrelease As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnRemoverelease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRemoverelease As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblMoviesAUR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMoviesAUR As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAURMovieName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAURMovieName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtMovies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMovies As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblAURMovieRelease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAURMovieRelease As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlReleasetypemovies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlReleasetypemovies As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblAURMovieGenre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAURMovieGenre As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlGenremovies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlGenremovies As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblAURMoviePrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAURMoviePrice As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrice As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnAddMovie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddMovie As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblUpdateMovie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUpdateMovie As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMovieSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMovieSelect As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlUDMovieSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlUDMovieSelect As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''UDMovies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UDMovies As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lblMovieUDReleaseType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMovieUDReleaseType As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlUDRelease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlUDRelease As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''UDReleaseType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UDReleaseType As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lblUDgenre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUDgenre As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlUDGenre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlUDGenre As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''UDGenre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UDGenre As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lblUDprice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUDprice As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtUDprice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUDprice As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnUpdateMovie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateMovie As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDeleteMovie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteMovie As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblTaxUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTaxUpdate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTaxAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTaxAmount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtUpdateTax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUpdateTax As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnUpdateTax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateTax As Global.System.Web.UI.WebControls.Button
End Class
